name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: [macos-12, ubuntu-22.04, windows-2022]
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S. -Bbuild
      - name: Build
        run: cmake --build build
      - name: Test
        working-directory: build
        run: ctest
